name: Hello World Action

# Trigger the workflow on push events
on: 
  push:
    branches:
      - main  # You can replace 'main' with the branch name you want

jobs:
  say-hello:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello World
      run: echo "Hello, World!"
